/* 
 * Morgan Yeh
 * 2025/01/02
 * Array of scrambles for all ZBLS cases (unformatted)
 */

const scrambleArray = [4,
    "D R F' U R' U' R F R' D'",
    "L U B' U' R U R' B U' L'",
    "B' R2 F R D R' D' F' R2 B",
    "R U R L2 U2 D2 R2 L2 D2",
    4,
    "R' F2 D' L' F L F2 D F' R",
    "F U' R' U2 F' L' U L U2 R",
    "B2 L2 F B2 R' F' R B2 L2 B2",
    "L2 B2 L2 F R' F' R L2 B2 L2",
    4,
    "F U' B U B' R' F' U' R",
    "R U' L U B U B' R' U' L'",
    "F B' R' U R U' R' F' U' R B",
    "L F U F' U' L' U2 R U R'",
    4,
    "D' L D F' R' D' L' F D R",
    "L U L' F B' R' F' U' R B",
    "F2 R' D' F D F L' U L U' R",
    "F' U F U' R' U' F' U F R",
    4,
    "L F R' F R F' R' F' R L'",
    "F R' U' D B2 U B2 D' F' U R",
    "B U L U2 L' U F B' R' F' U R",
    "R B U B' U R' U' F' U2 F",
    4,
    "R L' B R B R' B' R' L",
    "F2 B D' L D L2 F L2 F B'",
    "R2 D2 F' B R2 U' L U' L2 F B'",
    "R' L F' R F R' F R L'",
    4,
    "L U F U' F' L' U' F R' F' R",
    "B U L U' L' B' U2 F R' F' R",
    "R2 D' B' D R2 U' R U D' B D R'",
    "F U R' U2 D2 L2 U' L2 U2 D2 F' R",
    4,
    "B L F' L F L2 F B' R' F' R",
    "R' F' L F2 L' F2 R2 U2 R' F",
    "F R2 F' B' R' B R' U2 B' R B R'",
    "R B U2 F2 L2 F L2 F2 B' R' F'",
    4,
    "R U F' L' U' L U F U' R'",
    "F' U' L F L2 U B L' B' L2",
    "L B' L' F' U' F U L B L'",
    "D' F' R U' F U F' R' F D",
    4,
    "R2 F2 D' L' F L F2 D R2 F'",
    "F R2 D B R' B' R2 D' R F'",
    "D R' F B' R F' R' B R D'",
    "B2 L2 B2 R' F R F' B2 L2 B2",
    4,
    "L2 F' D' L' U' L D F L2",
    "B U' F' U2 F R U' R' U' B'",
    "R B L U' B' R B L' B' R2",
    "F' U2 R' F R U' R' F' R F",
    4,
    "R B U L U L' B' U2 R'",
    "B' R2 F D R' D' R' F' B",
    "F D R F' U' F R' D' F'",
    "D B' D' R F D B R' D' F'",
    4,
    "L2 D F D' F' L2 U L F L'",
    "R' D' F2 U' R' F R F2 U D R",
    "F' U2 B' R B' D2 L' D2 B2 R' U F",
    "L U' F2 U' F U F U F L'",
    4,
    "R L2 D' B D R2 L2 F R U' F'",
    "L F' U' F' U' F' U F2 U L'",
    "B L D' F L F' L' F' D L' B'",
    "F' B D L' F' L' F L D' F B'",
    4,
    "R U R' U' R' F R F2 U' F",
    "F' R U2 L' U L U2 R' U2 F",
    "L2 D F' D' R2 L2 B' R' U B U' R'",
    "F U F' L' U' L F U' F2 U' F",
    2,
    "R' D' L F' L' U F2 U F2 U' D R",
    "R' D' L F' L' D R2 U R'",
    4,
    "F2 L D F' D' F2 L' F",
    "B U2 F' B' U' F B U2 B'",
    "D2 F2 B2 U2 F' D2 F2 B2 U' F",
    "B' R2 B' R2 F' B U2 B U' F",
    4,
    "F' U R U B U' B' R' U' F",
    "B L' F B L' D' L D F' L B2",
    "R2 D2 F B' L2 D' R D' R F' B",
    "D2 F' B R2 U L U' R2 L' F B' D2",
    4,
    "F' R U2 L' U L U2 R' F",
    "R U L' U2 L U2 R' L F' L' F",
    "B' R' U R F' U B L U' L' F",
    "D R U F' L' U2 L U2 F R' D'",
    4,
    "F' R U2 R' U' F' L' U' L F2",
    "R' U' R U R B' R' F' B U F",
    "B U F' U L U' L' U' B' U F",
    "D' F' R U2 B U' B' U' R' F D",
    4,
    "D' L D R' D' F L' D R",
    "L F2 U F U' R' F2 R L'",
    "R' D L D2 F D R' D L' D' R2",
    "F2 U2 R' U' F U R L' U2 L F2",
    4,
    "D' F2 U R' F R U' F2 D",
    "R2 D L' B L U' B2 U' B2 U D' R2",
    "D2 L2 D R2 U2 D2 L B L D' R2",
    "L2 U2 R2 D' L' B L D R2 U2 L2",
    2,
    "R D B2 U' R B R' U B2 U D' R'",
    "R' U D' F2 U F2 U' L F L' D R",
    4,
    "F U R' F2 R2 U' R2 F' R L F2 L'",
    "F U L2 F2 R L' U2 L' U' R2 F' R",
    "F U L' F2 R L' U2 L2 U' R2 F' R",
    "F U' B2 R L' D2 B2 L U' R2 F' R",
    4,
    "R F2 L F L' U' F2 R' F'",
    "L' U2 R L U R' L' U2 L",
    "D2 R2 L2 U2 R D2 R2 L2 U R'",
    "F R F2 U L F' L' F2 U2 R'",
    4,
    "R U2 R' L F R' F' R L'",
    "L' U F R' F' R2 U' R' L",
    "F' U R B U B' U' R' U' F",
    "F B' R' D R' D L2 F' B D2 R2",
    4,
    "F U F' U' L' U' R U' R'",
    "B L U L' U' B' U2 R U' R'",
    "D2 F R U R' U' F' D2 R U' R'",
    "R B U B' U' R' U R U' R'",
    4,
    "F R' F' R F' L' U L U2 F",
    "R U R' F' U F U R U R'",
    "R2 B' R' B U R' U2 R U R'",
    "F' U2 F U2 F' U' L' U' L U2 F",
    4,
    "D B' D' F D R' B D' F'",
    "B' R2 U' R' U F R2 F' B",
    "R F R' D B' R' B' D B2 D2 F'",
    "F D' B' D2 R' D' F D' B D F2",
    4,
    "L F U F' U' L' U2 R U' R'",
    "D R B U B' U' R' D' R U' R'",
    "R F U F R' F' U' R F' U2 R'",
    "F' U' F R U2 B U2 B' U2 R'",
    4,
    "F' L F' L' F L' U2 L F R U R'",
    "F' L' U' B L2 B2 R B' R' B2 L' F",
    "R U B' R2 D' R' D R' B U2 R'",
    "R B L2 F' L' F L' U2 B' U R'",
    4,
    "R B2 L' B' L U2 B' U' R'",
    "R' U D' F2 U' F2 U' L F' L' D R",
    "L F U2 F L D F' D' F' L' U2 L'",
    "L F U2 F' U' F' U L F L' U2 L'",
    4,
    "B U R B' U2 B R' U' B'",
    "R U R' U2 R' F D R' D' R2 F'",
    "F' L' U L U2 F U2 R U' R'",
    "R U' R' L F2 R' F2 R2 L' U' R'",
    2,
    "D2 L U' F U F' U L' D2 R U R'",
    "R U' B U B' U R' U2 R U R'",
    4,
    "B2 D' R D F B R' F' U' R B",
    "L2 D2 B' R B D2 R U R' U' L2",
    "F' U R' L D F D' R L' U' F",
    "D' B' D R D' B D F R F' R'",
    4,
    "R B' R' B' R' D B D' B' R B2",
    "F' B U F' U L U' L' U' F2 B'",
    "F R B' L B R2 B' L' F' B R",
    "R U' R' U' F' L' U L U F",
    4,
    "R2 B2 D B D' R' B U' R'",
    "F' L' U L U' F U2 R U' R'",
    "F R' D' F D F' R2 U R' U' F'",
    "R U' R' U2 L F U F' U' L'",
    4,
    "R2 L2 D2 R D2 L' F R F' L'",
    "D2 R2 L2 U2 R D2 L' F R F' L'",
    "F' R' F' L F R L2 U2 L U2 F",
    "R' L F2 R F2 R' F R F' L'",
    4,
    "R U2 R' U D2 L U F U' F' L' D2",
    "R U2 R2 F' U F L U F' U' F R L'",
    "R U' L F U' R' U R F' U' R' U L'",
    "R B L U' L' U2 B' U B U' B' R'",
    2,
    "R U R' U2 B U' F' L' U2 L F U B'",
    "R U R' U L F' L' U2 L F L'",
    4,
    "B' R2 F R2 F' B U F' U F",
    "F B2 D2 F D2 F2 B2 U F' U F",
    "F2 B L2 F L2 F B' U F' U F",
    "F' U2 L' U L' B L B' U' L F",
    4,
    "L' B2 R B R2 U R2 U' R' B L",
    "R U R2 U' F' U2 F U2 R B U' B'",
    "R' U' D B2 U B2 D' F' U F R",
    "B' R2 F R D R2 D' R2 F' R B",
    4,
    "D L D' F' D L' D' R' F' R F",
    "L F2 U' R2 B' R' B U R' F L'",
    "R U' F B' D' R' D F' B U R'",
    "F U2 L F' L B L B' L2 F' L'",
    4,
    "F' L' F' B L2 B' L2 F L F",
    "B' U' R2 U B U' R' U' R2 U R",
    "F2 L F2 U F D F' U' F2 D' L' F2",
    "R' F2 L F L' U' F2 R F' R' U R",
    4,
    "R' F R F' U F R' D' F D F2 R",
    "F' U F U2 B' R' U' R U B",
    "F2 L2 D' L' D F L' U F",
    "R U' R' U F R' F2 U' F U R",
    4,
    "R2 B' R' B U' R' F R' F' R",
    "F R' F' R2 U2 R' F' U L F' L' F2",
    "R2 B' R' B U' R' F' U L F' L' F2",
    "F R' F' R2 B U B L' B' L B' U2 R'",
    4,
    "F' D2 R2 L2 U2 D2 R2 L U L F",
    "D F' U2 L' U2 L U2 F D' R U' R'",
    "R U2 B L U2 F U' F' L' U2 B' R'",
    "D2 F' U2 L' U2 L U2 F D2 R U' R'",
    2,
    "F2 L F L' U2 F U R U R'",
    "F' U F L' U R U' R2 L F R F'",
    4,
    "R U R L2 D2 R D2 R L2",
    "L F R' F2 R F2 R' F R L'",
    "R2 L' B R' B2 R B2 R' B R' L",
    "F' L' U2 L U2 L' U L U' F",
    3,
    "R2 B' R' B2 L U' L' U2 B' U' R'",
    "R2 B' R' B U2 R' U' R U' R'",
    "R2 D B' L' B' L B2 D' B' R' B R'",
    4,
    "L2 F2 L2 B L' B' L' F2 L2",
    "B2 R2 B' L' B' L B2 R2 B2",
    "F2 R2 F L' U L U' F' R2 F2",
    "R F U' D B U B' D' F' R'",
    4,
    "F' U' F U2 F' U2 F2 R' F' R",
    "R U' R' U R' F' L F2 R F L' F2",
    "F' U' B L2 F' L2 F' B' R' F' R",
    "F' R' L F' D F2 D' F' R F' L' F2",
    4,
    "R2 B2 D B D' R' B U2 R'",
    "F' U L F' L' F2 U2 R U2 R'",
    "F R' F' R U R' L F2 R F2 L'",
    "R U' B U L U' L' U2 B' R'",
    3,
    "R U R' U2 R' F R F2 U' L' U L F",
    "R U R' U' F2 L F L' U2 L' U L F",
    "F2 L F L' U2 L' U L U' L' U L F",
    4,
    "R U' R' U2 D B U' L U L' U B' D'",
    "R U' R' D' F U' R U R' U F' D",
    "F2 L F2 U' R U R2 F' L' F2 R F'",
    "F2 L F' R2 D R D' F2 L' F2 R F'",
    4,
    "F2 U' R' F R F2 U' R' L F R L'",
    "L F R U2 R' L F2 R' L' F' R L'",
    "L' U2 R2 B' R2 U2 R B R' L",
    "L F' R2 D2 L2 B2 L2 D2 R F' R L'",
    4,
    "F' U' F U2 B' R2 F R2 F' B",
    "B' R' F2 B' D2 F' D2 B R' F' B",
    "R B U' B' U2 R' U2 F' U2 F",
    "F2 B L' B D2 F' D2 F2 B' L' F B'",
    4,
    "F' U' L' U' L' B L B' L F",
    "B' R U D2 L2 U L2 U2 D2 R' B",
    "R2 B' R U' R2 U R' B R2 B' R2 B",
    "L' U' B U L U' F2 L2 B' L2 F2",
    4,
    "R2 L' F B' D2 B' D2 F' R2 B2 L",
    "R' D2 R L' B L2 B' R' L' D2 R",
    "L F B' U2 F2 B U2 F' L2 F2 L",
    "B2 R B R' U' R2 B' R2 B2",
    4,
    "L' B L U' F' U L2 B' L2 U2 F",
    "F' L F' L D' L' D L' F U' F",
    "F' U' B L F' D F' D' F L' F2 B'",
    "F' L F2 L' F2 U2 R' F R F R' F' R",
    4,
    "F2 L2 D' L' D F L' U2 F",
    "R U' B' R B R2 U2 F' U2 F",
    "F' U L' U2 L F U2 R U R'",
    "R' F R F' U B' R2 F R2 F' B",
    4,
    "F' U F U2 D' F U' R U' R' U F' D",
    "F' U F D B U' L U' L' U B' D'",
    "F' U F U R U' R' U R' F R F'",
    "F' U F U R U' B U' B' U R'",
    4,
    "F B2 R' D2 R F2 B2 L F U L U' L'",
    "F' U2 R' F2 R F U' F2 U' F2 U F2",
    "D' F L F2 L' U2 F' L2 U' L2 D F2",
    "F' L' U2 L U' F R U B U B' R'",
    4,
    "L' B' R' B L U F' U F B' R' B",
    "F R' F' D' F D' L2 F' D2 R2 B' R'",
    "F2 R' F2 L F' R L' U R' F R U F2",
    "L F' U2 R' U2 R U R' U F2 R F L'",
    4,
    "R U2 B U B' R' U' F' U F",
    "F' U F U R U2 B U B' R'",
    "R U F' L' F R' F' U L U F",
    "F R' D' F D F2 R U2 F' U F",
    4,
    "F' L' U L U2 F2 U R U' R' F'",
    "F R' F D' F' D R U R U' R' F'",
    "R U R' D2 F U R U' R' F' D2",
    "B U L U' F2 L F L' F L' B'",
    4,
    "F' D R2 U R2 D' F2 U F L F2 L'",
    "R U2 B U2 R' F' R B' R' U F",
    "R' F D R' D' R F' R2 U R'",
    "F R' D' F D F2 R2 U R'",
    4,
    "F R2 L2 D2 L B2 L' D2 R L2 F' R",
    "F' R L' U2 B2 R B2 R L2 F2 L' F' R",
    "F D2 R B2 R' U2 L' B' L B U2 D2 F'",
    "F B2 R L' D2 B2 L U2 R' U2 R' F' R",
    4,
    "R2 B' R' B U2 B U' B' R'",
    "F R' F' R U F U R U' R' F'",
    "B L U' L' F' B' R' U R U F",
    "L' B L B' U' L F' U F2 U F' L'",
    4,
    "R' F R D R2 B R2 D2 F L2 D F2",
    "L U2 R U R' L F' L' U2 F L'",
    "F' B L' B' L' U F L' U' L U L",
    "R U2 B U2 B' R' F' B U' F U B'",
    2,
    "F U L F2 L' U2 F R2 D R D' F2 R",
    "F U L F2 L' U R U R2 F' R",
    2,
    "F2 R U' R2 F R U R U R2 F2 R",
    "R U R2 L F' R L' U2 L F' L'",
    4,
    "R F' U' F U' F' U2 F U' R'",
    "F' U2 L' U' L F U R U' R'",
    "D R F' U' R' F U' R F R' D' F'",
    "R F' U' R' F U' F' R U F U' R'",
    4,
    "R U2 R' F R U R2 D R' D' R2 U' F'",
    "R U' R' U' R U' B U B' R2 F R F'",
    "R U' R' F R' F' R F2 L F L' U' F",
    "R F' U' F U' F' U' B U' F U2 B' R'",
    4,
    "R F' U' F R' F D R2 D' R2 F'",
    "F' U L F L' U2 F2 R' F' R F'",
    "D2 R U' R' F R' F' R D2 R U' R'",
    "D' R U' R' F R' F' R D R U' R'",
    2,
    "R U' R' U F' U2 L' U' L F2 R' F' R",
    "F' U2 L' U B' U' B U' L F2 R' F' R",
    4,
    "L U L' B' U R U' R2 U' R B",
    "R B' R B U R' F' U2 F R U' R2",
    "R2 U R' F' R' U' R U' F R U' R2",
    "L' B' U B R L F U' F' U' R'",
    4,
    "D R U' R' U' F' U F D' R U' R'",
    "R U' D' R' U' F' U F R U' D R'",
    "R D2 F' U' L' U L F U2 D2 R'",
    "R D' F' U' L' U L F U2 D R'",
    4,
    "F' L F' L' F R U R' U' R' F R",
    "F' B2 L F R' D R F2 L' B2 U' F2",
    "F U2 F' U' R L' U' R' L F U' F'",
    "R' F2 L D F' L D L' D' R L' F'",
    2,
    "R U2 L F' L' F R' F' U2 L F L'",
    "F R' F' R U2 L F' L' U L F L'",
    4,
    "L F2 D F D' L' U F2 U2 F'",
    "F U F2 U B2 D2 F' U2 F2 B2 D2",
    "B' R2 B' L2 F2 D' F2 L2 B R2 B",
    "R F R2 D B R' B' U R2 U' D' F'",
    2,
    "R U R' F R' F' R2 U R' U' R U R'",
    "L' U2 L U' F U2 F L F2 L' F U' F'",
    3,
    "F' U F R U R B' D' R D R2 B R'",
    "F' U F R U B U2 L U L' B' U R'",
    "F' R B U B' U' R' U F U2 R U' R'",
    4,
    "R U' R' U F R' F' R2 U2 R'",
    "R' F D R' D' R F' R2 U2 R'",
    "F' U F U R' L F2 R F2 L'",
    "F R' D' F D F2 R2 U2 R'",
    4,
    "F' U' F' B L' D' L2 D L' F2 B'",
    "D' F R U2 R' U2 F' D F' U' F",
    "R U' R' U2 F' L' U' L U' F",
    "F R L' U2 R' L U2 R' F2 R U' F",
    2,
    "B U' F' L' U2 L F U B' R U2 R'",
    "L2 F' D' L' U2 L D F L2 U R U2 R'",
    3,
    "R' F R F' U F' U L' U L F",
    "F2 L2 D' L' D F L' U L' U L F",
    "R B L U L' U B' U B' R B R2",
    4,
    "R2 B' R' B U2 R' U R' F R F'",
    "R2 B' R' B U2 B U' B' U R'",
    "F' U' F U R2 B' R' B U2 R'",
    "F' U' F U2 F R' F' R2 U R'",
    4,
    "R B' U2 B U2 R' U' B' R U R' B",
    "D B U B' U2 B U B' D' R U R'",
    "R U R' F' L' U B' U B U' L U2 F",
    "R U' R U2 R2 F U' F2 D R2 D' R2 F",
    2,
    "R' D' F D R U' D' F U F' D",
    "R U2 L' B R B R' B' L U R'",
    4,
    "R2 B2 D B2 R' U R B' D' B R2",
    "R U' B L' B L B' U B' U R'",
    "D B U' L U L' U B' D' R U R'",
    "R U' B U B' U R' U' R U R'",
    4,
    "R D' F' U L' U2 L U' F U' D R'",
    "F' U2 L' U' L F U' F' U2 F",
    "F R' D' F D F' R F2 U2 F",
    "R' F D R' D' R2 F2 U2 F",
    4,
    "R U2 B U' B2 R D B' D' B2 R2",
    "D R' F' U2 F U2 R D' R U R'",
    "F' L' U2 L U' L F' L' F U' F",
    "R U B L U2 F U F' L' B' U R'",
    4,
    "R U' R' U2 L' B' R B' R' B2 L",
    "B' U' R L U' R2 U L' U R B",
    "B2 R B2 L U L2 B L B R' B2",
    "R U' R2 L F2 R' F' R F' L' U2 R",
    4,
    "R U' R' U' R U' B U B' U' R'",
    "R U' R' U' R2 B2 D B D' R' B U' R'",
    "R U' R' F' U L F' L' F2 U2 R U' R'",
    "R2 U B' U' R' U B U' R' U2 R U' R'",
    4,
    "R2 B' R' B U' R' U F' U' F",
    "F R' F' R2 U B' R B R' U R'",
    "R2 B' R' B U2 B' R B R' U R'",
    "F R' F' R2 U2 R2 F2 D' F' D R F'",
    4,
    "R F U F' R' F U' R' F' R",
    "F' B' R' U R F2 R' F' U' R B",
    "R F R' F' R U R U' R' U R'",
    "R2 F R2 F' R U R2 U' R2 U R'",
    3,
    "F' U' L2 D' L U' L' D L2 F",
    "F' R U R2 F D R2 U' R D' R2",
    "B' R U' D' B' D R' D' B U D B",
    4,
    "L F R' F2 R L F' R' F R L2",
    "L F L F R' L' F2 L F R L2",
    "R L' U' B U R B R' B' L U' R'",
    "F' R B U B' U' R' U F R U' R'",
    4,
    "R' L D2 L D2 L' F' L' F R",
    "F2 U2 L F L' F' L' U2 L F2",
    "R L' U2 L U2 R2 L F' L' F R",
    "R2 L2 B2 L B2 R L2 F' L' F R",
    4,
    "L F2 U F' U' R' F2 R L'",
    "R U2 R L' D B' D' R2 L",
    "L F2 U F' U' F2 R L' U2 R'",
    "R L' B2 R B2 D B' D' R2 L",
    4,
    "L F U F2 B' R2 F' R2 B U F L'",
    "L F U B L2 F' L2 F2 B' U F L'",
    "L2 F L' F R U2 R' F L'",
    "L F R L' U2 F R' F R F2 R' F2",
    4,
    "F D2 B' R' B2 R B2 R B D2 F'",
    "F D2 B' L' D2 R D2 L B D2 F'",
    "F U2 F2 U' R' F R F2 U' R' F' R",
    "R' L D2 B' D F D' B D2 R L'",
    1,
    "R U' R D L' B' L D' R' U' R'",
    4,
    "F' R' U' R F R' U F R F'",
    "R U B L U' L' U2 B' U R'",
    "R L F U' F' R2 F R U F' L'",
    "F' U2 L' U' L F U R U R'",
    4,
    "D' F' R U B U B' U2 R' F D",
    "F2 L D F U F U' F2 D' L' F2",
    "U F' L U F U' R' F R F2 L' F",
    "R U' B' R' F R B R2 F' R",
    2,
    "R' U' F D R D' B2 L' D L F' B2",
    "R' L F R F' R' F' R F R' F R L'",
    2,
    "R2 B' R' B U' R' U' R U' R'",
    "F R' F' R U2 L U2 L' U' L U' L'",
    4,
    "R' F R2 F U F' R' F U' F2",
    "R U B U B L' B' L B' U R'",
    "L F' U F2 U' F' L' U2 R U R'",
    "R2 L' B' R' U R' U' R B L U' R'",
    4,
    "R U' R' U' F' R U B U' B' R' U F",
    "R U' R' U' D F' U F U R U' R' D'",
    "R U' R' U' D2 F' U F U R U' R' D2",
    "R U' R' U' D' F' U F U R U' R' D",
    4,
    "R U2 B2 D B D2 R D R2 B",
    "R U2 B2 D B D' B R2 U R",
    "R' F D R' D' R2 F L F L' F",
    "F' U2 L2 B L B2 U' B L U' F",
    4,
    "L F R U2 R2 F' R2 U2 L' U R'",
    "L F R L' U2 R' U L F L'",
    "L F' R' F2 R L' U' L F L'",
    "L' U2 R2 B' R2 U2 R B L U R'",
    4,
    "L' F' L2 F R F' L2 F L U R'",
    "B2 D' L' B2 U' R U B2 L D B2",
    "R U R B R' F R B' R' F' R'",
    "F R2 F' D' F D R D' F' D R",
    4,
    "R L' B U2 B' R' U R U2 R' L",
    "F' R2 L' B' R' B U R2 L F R",
    "F' L' B' R' U R U B L F",
    "R L' B U2 B' R' U' R' L F2 R F2",
    4,
    "R U' R' U2 R U' B U B' R'",
    "R U' R' F' L' U L U' F",
    "R U' R' U' F' U L F' L' F2",
    "F' U' R B U' B' R' F' U F2",
    4,
    "L F' L' F R U F U' F' R'",
    "F' R' F R U R' F' R U F",
    "L F' L' F' L D F D' F' L' F2",
    "F' R' F R U F2 U L F' L' F'",
    2,
    "R2 B' R' B U2 R' U2 R U' R'",
    "R2 B' R' B R L' B2 R' B2 L U' R'",
    4,
    "R B L U' L F' L' F U2 L' B' R'",
    "R B2 L' D' B D B2 L2 U L' B' R'",
    "L F2 R F2 R L' U2 B' R' B U' R'",
    "L F' U L F L' U' L' U' R U2 R'",
    4,
    "R U R' U F B' D R' D' F' B",
    "R U L' B R B' R' B' R' L",
    "L' B' U B R U L' D' B' D R' L2",
    "R U L' B U' B2 L' B' L U B R' L",
    1,
    "R U R D L' B' L D' R' U R'",
    4,
    "R U' B L' B L B2 U R'",
    "R2 U R2 F D' F D F2",
    "F R' F' R U' R B' R B R2",
    "L2 F2 B2 R2 L2 F2 D B D' B R2",
    4,
    "B L' B' U R U2 B U L B' R'",
    "R U R' U2 D R U B U' B' R' D'",
    "R U R' U B U L U' L' B'",
    "R U R' U' F U R U' R' F'",
    4,
    "F' U L' U B' U B U2 L F",
    "L F' U D' L' U L U2 D F L'",
    "R F R2 D B' D B D2 F' R",
    "F R' D2 L D L' D F2 R F",
    4,
    "R' U' B U F U' B' U R F'",
    "D B D' R' F R D B' D' F'",
    "R U' R' U2 B L U L' U' B'",
    "F2 U' L' U L F L' U' L F",
    4,
    "F' U' L' U L U F U2 R U R'",
    "F' U' F B' U' R U R U' R U R2 B",
    "F' U' L' U L F R U2 B U B' U R'",
    "F' U' L' F U F' U F U2 F' U L F",
    2,
    "L D' L' D R' D' L F D R L'",
    "R' D' R U R' L F L' D R",
    4,
    "R U' R U B U' B' R2 F R' F' R",
    "F U R U' B' R' F2 R B R' U' F",
    "F U2 L' U' R U L U2 R' F2 U' F",
    "F' R' F' U F2 U' F' R B U' F B'",
    4,
    "F' L' U2 L F R B U B' R'",
    "R' F R F' U2 R' L F R F' L'",
    "R' F' L' F R F' U B' U2 B L F",
    "F' L' U2 L F L F2 R' F2 R L'",
    4,
    "F' U F' L F L' U' F R U2 R'",
    "L F' U F2 U' F2 U F U' L'",
    "R U' R' U' R' L F2 R F2 L'",
    "R' F D R' D' R2 F' R U2 R'",
    2,
    "R U R' U' R B' U' R' U R B U R'",
    "R U R' U' F' U L F U F' U' L' F",
    4,
    "R U2 B' R B R2 U2 R U' R'",
    "R U' R2 F R F' U R U' R'",
    "F' U F' L F L2 U' L F R U' R'",
    "F' U2 L2 B L B' U2 L F R U' R'",
    4,
    "R U L' B U' B2 U R B R2 L",
    "R U R' U F' U2 B U L U' L' F B'",
    "R U R' U2 R U2 R' U2 F' L' U L F",
    "R U L' B2 R B2 R' L U R' F' U2 F",
    4,
    "R B U2 B' R' F D F' U2 F D' F'",
    "F2 L F' R U' R' U F' L2 U L",
    "L F2 R' F2 R F' L' F U2 F U2 F'",
    "L F2 R' F2 R F' L' B L2 F L2 B'",
    2,
    "L' U2 R B' U' R' U R2 B R' U2 R' L",
    "R' F R2 U R' U' F' R U2 R'",
    4,
    "D2 B' L2 D2 R' D2 L2 B D2",
    "R2 U R2 B' R' B U R2 U2 R2",
    "R2 U2 F R' F B2 D2 L2 D2 F2 B2",
    "F2 U2 R2 D2 B' L' B D2 R2 U2 F2",
    4,
    "R U2 B' R B R2 U2 F' U2 F",
    "R U' R2 F R F' U F' U2 F",
    "F' U F' L F L2 U' L U2 F",
    "F' U2 L2 B L B' U2 L U2 F",
    3,
    "R U R' F R' F D' F' D F' R",
    "R U2 F' L F U' R' U F2 L' F2",
    "F R' F D' F' D F D' F' D F' R",
    4,
    "R B' U' R' U2 R U2 B L U' R' L'",
    "R2 B U' B' U2 R' F' L' U L F R'",
    "F' U L F U F' U' L' F R U R'",
    "R D' B' U' R' U R B U2 D R'",
    4,
    "R U' R' U R B U' B' U' R'",
    "R U' B U' L' B' L U L U' R' L'",
    "R U' B L U' F' L' B' L F R' L'",
    "R B U' L' U' B' U B L B' U' R'",
    4,
    "R2 B' R' B U2 R' F R' F' R",
    "F' L' U L2 F' L' F L F' L' F2",
    "F' L' U2 B L' B' L2 U2 F2 R' F' R",
    "R U F R' F' U2 R U2 R U2 R2",
    4,
    "R2 B' R F' U F U' R B2 U' B'",
    "F' U L F2 R' F L' F2 R2 U' R'",
    "B' R2 F R2 F' R B R' U2 R' U2 R",
    "B' R2 F R2 F' R B L' B2 R' B2 L",
    2,
    "R2 D L' B' R' B2 L U2 R2 D' R",
    "R U2 B U' B' R' U' R U' B U2 B' R'",
    4,
    "F' U2 F B' R' F R' F' R2 B",
    "B U' R' F R F2 U B' U2 F",
    "F U2 F B' R2 F2 R F R' F' R2 B",
    "F2 U2 F B' R2 F R F R' F' R2 B",
    2,
    "R2 B' R' B U' R' F U R U' R' F'",
    "F R' F' R2 U2 R' F U R U' R' F'",
    4,
    "F' L' U L U2 F U' R U2 R'",
    "R U R' U R L' B2 R B2 R2 L",
    "R U R' U R2 L2 D2 R D2 R L2",
    "R U R' U' R B L U' L' U2 B' R'",
    4,
    "F' U' F2 U R U' B' R B R2 F'",
    "F' U' F2 U2 F' U' F R U' R' F'",
    "R U R B' R' B R' U' R U2 R'",
    "F' U' F2 U R' F R F' U' F'",
    4,
    "R U' R' U F' L' U' B' U' B L F",
    "R U B L U L' B' U R' U F' U2 F",
    "R U' R' U F' L' U L F U' F' U2 F",
    "R U' L2 B' R D R D' R' D' B R2 L2",
    4,
    "R U B U B' R' U' R U R'",
    "R U2 R B' R' U2 B U B' U B U R'",
    "R U2 R B' R' B U R' U2 R U R'",
    "R U2 R' U F R' F' R U2 R U R'",
    4,
    "R U' R L2 D2 R D2 L2 F R F'",
    "R U' R' U2 R U B' R B R2",
    "R U' L' B2 R B2 R L F R F'",
    "F' U2 L' U' L F R U2 R2 F R F'",
    4,
    "R U' R' U L U F U' F' L'",
    "R U' R' U2 B U L U' L' B'",
    "R U' R' U' R U B U' B' R'",
    "R U' B U' L' B' U' B U L B' R'",
    4,
    "F R' F R L F2 L2 U2 L",
    "F R' F' L2 D2 R' D2 R2 L2",
    "F' U L F' L' F2 U' R U2 R'",
    "F' L' U L U' F U' R U2 R'",
    4,
    "R U2 B' R B R2 U F' U' F",
    "R U' R' U F2 L F L' U2 F",
    "R U B L U' L2 B L B2 U2 R'",
    "F' U2 L2 B L B2 U' B L U F",
    4,
    "F' U' F U B' R2 F R2 F' B",
    "F' U' F U' F B' R2 F' R2 B",
    "F' L F2 D F D' L' F U2 F",
    "R B U' B' U2 R' U F' U2 F",
    4,
    "R' U' F U R U' F2 U2 F",
    "R U R2 U2 R U R' F' U F R",
    "F' U2 F U R U2 R' U F' U2 F",
    "F' U2 B L U L2 U' L B' U2 F",
    4,
    "F' B L' U L' U' L U L2 U' F B'",
    "L' U2 R' F D R' B' D' R2 F' U2 L",
    "B' U2 F2 L D2 R' D2 F2 L' U2 B",
    "R' U2 D' F U2 F' U2 F' U2 D R",
    4,
    "R U R' U' R2 B' R' B U2 R'",
    "R B' R2 D' R' D R' B U2 R'",
    "F R' F D' F' D F' R2 U R'",
    "F' L' U L U2 F2 R' F' R2 U R'",
    2,
    "L' U2 R2 L' D' B' D R2 L U2 L",
    "R' L D' F' D' L D2 L' F2 L' F2 R",
    4,
    "F D R2 U' R' U2 R U R2 D' F'",
    "D' F2 U F L' U2 L F' U' F2 D",
    "L F' D' L2 U2 L2 D F L'",
    "R U' B L U2 L' B' U R'",
    4,
    "R' F R' F' B' R2 B2 U2 B'",
    "F' U L2 B L B' U' L U F",
    "R L' U2 L U2 R' L F' L' U F",
    "R2 L2 B2 L B2 R2 L2 F' L' U F",
    4,
    "R U2 B2 L' B' L2 U L' B' U' R'",
    "F' U' L' B' U B2 L' B' L2 U2 F",
    "F' U F U' R2 B' R' B U2 R'",
    "F' U2 L F' L' F2 U' R U R'",
    4,
    "F U F2 U' F' L F' U F' U' L'",
    "U2 F' L' U L U2 F U' R U' R'",
    "U2 L U2 R U' L' U' L U R' U2 L'",
    "R U R' U' R' F D R' D' R2 F'",
    4,
    "B U' R U B U B' R' B'",
    "R B L U B' R' B L' B'",
    "F' U L F L' U' L' U L",
    "L2 F D F2 D' L' U F U L'",
    4,
    "F' B U2 B' U2 F B' R B R'",
    "D R F' R B' R' F B R' D'",
    "L2 F2 B2 R2 L2 F2 B R' B R'",
    "B' R' U R2 U' R' U' B L U' L'",
    4,
    "R U2 D B' R' U' R U B D' R'",
    "R U2 D2 B' R' U' R U B D2 R'",
    "R U2 D' B' R' U' R U B D R'",
    "R D F' L' U' L U F U2 D' R'",
    4,
    "R B L U L' B' U2 R'",
    "B' R D B U2 B' D' R' B",
    "L' F' B' D2 L' U2 L D2 F B L",
    "B U R2 F R F' U' R2 U2 B' R'",
    4,
    "R2 B2 D B D' R' B2 U2 B' R'",
    "F' U2 L' U B' U2 B L U' F",
    "L F2 R' F2 R U F U' F' L'",
    "R U2 R' U' B U L U' L' B'",
    4,
    "F' U2 F U R U' B U' B' R'",
    "R' L F R F R' F' R F' L'",
    "R B' R2 B R' U' R' U' F R' F'",
    "F' U2 F R B U' B L' B' L B' R'",
    4,
    "R U' R2 F R F L F L' U' F",
    "R U' R2 F R F' U' R' F R F'",
    "R U' R F D R F' U' F D' R F'",
    "R U' R2 F R F2 U L' U' L F",
    4,
    "F' L2 D2 R2 B U2 R2 D L2 D F2",
    "D' F' R U F U2 F' U' R' F D",
    "B' U' D R2 U D' B U' F2 U F2",
    "R F U F' L' U2 L F U' F' R'",
    4,
    "R B U' L' B' R' B L B'",
    "F' U2 F' L F' D F D' L' F2",
    "L2 U F' U' L' U' L F L2",
    "B2 R' D' R2 D B U' R' U' B",
    4,
    "R U2 B U B2 R B R' U' R'",
    "F2 L F2 L2 U B L' B' L2",
    "F' U L2 B L B' U' L F",
    "L F2 R' L F L' F R U2 L'",
    4,
    "R2 B L2 F' L' F L' U2 B' U2 R2",
    "R' L' B2 L' B L B2 R' L' B R2 L2",
    "R B' U2 B L' B L B2 U2 B U2 R'",
    "R2 U2 R' F R' F B2 L2 D2 L2 F2 B2",
    4,
    "F' L' B' U' B L U2 F",
    "L F' D' L' U2 L D F L'",
    "B' R2 B R U2 R' B' R2 B",
    "R U2 B U2 B' R' U F' U2 F",
    4,
    "F' L' U L' B L B' L F",
    "R U2 B U B' U R' F' U2 F",
    "F2 U L U F U' R' L' F R",
    "F' U F U2 R U R' F' U2 F",
    4,
    "R2 B' R' B R' F R' F' R",
    "F' U L F2 R' F' R F2 L' F2",
    "F R' L D F' R' D' R2 F2 L' F2",
    "F2 L D F' D' R' F' R F2 L' F2",
    4,
    "F' U F2 R' F' R U F R' F' R",
    "F' U F2 R' F' R' B' R' B U R'",
    "R L F L' B L U2 F' L' U2 B' R'",
    "F' U F U F' L' U L2 F' L' F2",
    4,
    "R2 U R' U' R2 L2 D2 R D2 L2",
    "F2 R' B2 L2 D L' D F2 L' B2 R",
    "R D2 R U R' U R U2 R' D2 R'",
    "R D' R U R' U R U2 R' D R'",
    2,
    "R2 B' R' B U2 R' U R U2 R'",
    "F R' F' R U2 L U L' U L U2 L'",
    2,
    "R2 B' R' B U2 R' U R U R'",
    "F R' F' R2 U R' U R U R'",
    4,
    "F' U F U2 L F U F' U' L'",
    "F' U F U' B L U L' U' B'",
    "F' U F U D2 F R U R' U' F' D2",
    "F' U F U D' F R U R' U' F' D",
    4,
    "R' F R F2 L' U' L U F",
    "R U R' U2 R U B U2 B' R'",
    "R U L' B' R D B2 D' B' R2 L",
    "R B' U' R U B U' R' U' R'",
    4,
    "R U R' U R B' R B R' U' R'",
    "R U B2 R B2 R' B U B2 U' B R'",
    "R U2 B U' L' U' B' U B2 L B2 R'",
    "R B' U R U B U' R2 U2 L U2 L'",
    4,
    "R U L' B' R B' R' B2 R' L",
    "R F' L' B L' B' L2 F U R'",
    "R U' R' U2 R B2 L' B' L B' R'",
    "R U' R' F' L F' L' F2 R U2 R'",
    2,
    "F B' D R' D' F2 B U' F R U' R'",
    "R2 B' R' B U2 R' U F' U F",
    4,
    "F R2 D2 B' D' B D' R2 F'",
    "R U R' U' R2 B' R' B R'",
    "F R' F' U' R2 B' R' B2 U' B'",
    "B U2 F' U2 F B' U' B U' B'",
    1,
    "L F' R' F' R F L' U' R U R'",
    2,
    "R U' R' U' R U B' R B R2",
    "R U' R' U' R U2 R2 F R F'",
    4,
    "R U R' D F R U R' U' F' D'",
    "R U R' D2 F R U R' U' F' D2",
    "R U R' D' F R U R' U' F' D",
    "R U' B L U' L' U' B' U' R'",
    4,
    "F' U F R2 B' R' B U R'",
    "R U R' F' U F2 R U R' U' F'",
    "R2 B' R' B U B U B' U' R'",
    "F R' F' R U F R U R' U' F'",
    4,
    "R U F' L' F R' F' U2 L F",
    "F' U F U' R U R' F' U2 F",
    "F' U F2 R' F' R U F' U F",
    "R U2 B U2 R' F' R B' R' U' F",
    4,
    "F2 U' F U' F' U2 F' R' F' R",
    "F' U F U2 F' L2 B L B' L F",
    "F' U F R B' R B R2 F' U2 F",
    "F' R U2 R' F2 L F L' F U F",
    4,
    "R B U' L U2 L' U2 B' U' R'",
    "R' F R F' U F' U2 F R U2 R'",
    "R U2 B U' L F U F' U2 L' B' R'",
    "F2 L2 D' L' D F L' U2 F R U2 R'",
    4,
    "R' B' D' R' D B2 U' B' U R2",
    "F2 U' B U' L' U L U F2 B'",
    "D2 F' R U R' U' R' F R D2",
    "D' R F U F' R' F U' F' D",
    4,
    "D' R U' R' F R' F' R D",
    "L F' R' D R' D' R F R L'",
    "R L F U' F' R' F U F' L'",
    "F2 L' U2 L U F U2 F' U' F2",
    4,
    "F' U' R B U B' U' R' F",
    "D R U R' U' F' U' F D'",
    "D2 R U R' U' F' U' F D2",
    "R U R' U R B U' B' U2 R'",
    4,
    "R F' U' L' U L F U' R'",
    "F' R' U' R F B L U L' B'",
    "D R U' R' U' F' U F D'",
    "D2 R U' R' U' F' U F D2",
    4,
    "B' U' B' D' R' D B U B",
    "F D F' U F B' R' B D' F'",
    "L' D' B' R' B' D B L U B",
    "L' B' D' R' B' D L B U B",
    4,
    "F D B' R F' B U' F D' F'",
    "B' U' L' B' D' B R B D L",
    "D L' B' R' B' R B R B L D'",
    "D2 L' B' R' B' R B R B L D2",
    4,
    "R2 U2 F L2 U R U' L2 F' U2 R2",
    "F' U2 F U2 F B' D R D' F' B",
    "D' B' R2 U' R U R2 B D",
    "B' R2 F R2 D R D' F' B",
    4,
    "R B' U' R B R2 L2 D F D' L2",
    "D R U R D L' B' L D' R2 D'",
    "D2 R U R D L' B' L D' R2 D2",
    "D' R U R D L' B' L D' R2 D",
    4,
    "R F B' D' R' D F' B R'",
    "F U F U F' U' F' U' F'",
    "L U' D F' U' F U D' L'",
    "B U2 D2 F' U' F U2 D2 B'",
    4,
    "R U B' U' R U B U' R2",
    "F U' F2 U F R' F2 R F2",
    "F2 U' F U F R' F' R F",
    "R' F R2 F2 U L F' L' F2 R'",
    4,
    "R U' B' R' U' R U B U2 R'",
    "F' U' F U' F' L' U L U2 F",
    "D F' U' F U R U R' D'",
    "D2 F' U' F U R U R' D2",
    4,
    "R F U F' R' L' B' U' B L",
    "F' U' B U L U' L' B' U2 F",
    "D F' R U F D B R' U' B' D2",
    "D2 F' R U F D B R' U' B' D",
    4,
    "R U' R' U2 F' L' U' L U2 F",
    "F' U2 R L2 B2 L B2 R' L F",
    "D F' U2 L' U2 L U2 F D'",
    "D2 F' U2 L' U2 L U2 F D2",
    4,
    "D2 B L F L F' L' F' L' B' D2",
    "D' B L F L F' L' F' L' B' D",
    "R' D' R U R' L F' L' D R",
    "L U B L D L' F' L' D' B'",
    4,
    "D F2 R U' R2 F' R2 U R' F2 D'",
    "D2 F2 R U' R2 F' R2 U R' F2 D2",
    "D' F2 R U' R2 F' R2 U R' F2 D",
    "F2 R U' R2 F' R2 U R' F2",
    4,
    "D R2 D L' B L D' R' U' R' D'",
    "D2 R2 D L' B L D' R' U' R' D2",
    "D' R2 D L' B L D' R' U' R' D",
    "L2 D F' D' R2 L2 B' R' U B R",
    4,
    "F' L' U L U2 F U' R U R'",
    "F' L' U B' U B U' L U2 F",
    "R U R' F R' F D' F' D R F'",
    "R U R' F R' F' R U F' U' F",
    4,
    "R U' R' F' U F' L F L' F",
    "L F2 R' F2 R L' U' F' U F",
    "R' L F2 R F2 L' U F' U F",
    "F' B L U L2 U' L B' U F",
    4,
    "R U F' L F R' F2 L' F U' F",
    "F U' B U B' R' F' U' R2 U R'",
    "R U R B' R' B U R' U2 R U R'",
    "R U R' U F R' F' R U2 R U R'",
    3,
    "R L' B R B R' B' L U R'",
    "F B' D R D' F' B U' R U R'",
    "F B' D R D' B R2 D R D' F' R",
    4,
    "R U' B' R2 D' R' D R' B U2 R'",
    "F R F B' D2 F' D2 F' B U R'",
    "F' L' U L U' F U' R U R'",
    "R U R' F' U F U' R U R'",
    3,
    "F' L' U' L U F2 R' F' R2 U R'",
    "R' F' U' F U R' B' R' B U2 R'",
    "F R' F' R U2 R U' R' U' R U R'",
    4,
    "R B2 U' B R' B' U B R2 B R2",
    "R U2 R' U' F' U2 F U' R U R'",
    "R U2 L' B' U' B2 U B' L U R'",
    "F' L F' L' F U F U R U R'",
    4,
    "F' U L' B' U2 B U' L F",
    "R B U' L U2 L' B' U R'",
    "R B U B' R' U2 F' L' U L F",
    "F' L' U2 B' R' U R B U' L F",
    4,
    "R B U' L U' L' U B' U2 R'",
    "R B U' B' U2 R' U F' U' F",
    "F' U' F R U' B' R B R' U R'",
    "F' U' F R' F R F' U' R U R'",
    4,
    "R B U' B' U2 R' U2 R U' R'",
    "F' U' F U2 F' U2 L' U' L F",
    "R' F2 D' F' D R F' U2 R U' R'",
    "F' U' L' U L U2 F R U2 R'",
    4,
    "R U B' U F' U' F R B U R2",
    "R U2 R' L U L F' L' U' F L'",
    "R2 L' B2 R' B2 L B U' B' U' R'",
    "L F2 R' F2 R2 L' B U' B' U' R'",
    4,
    "F' U2 F L F2 R' F2 R L'",
    "B' R2 F R2 F' B U2 R U2 R'",
    "R U' B L U2 L' U2 B' U' R'",
    "F2 B2 D2 F' D2 F' B2 R U2 R'",
    4,
    "F' U' F R U' R' U F' U' F",
    "U' R B U' B' U R' U F' U' F",
    "R U2 B L U' L2 B L B2 U2 R'",
    "R' F R U D' L2 U' L2 U' D F'",
    4,
    "R U2 B U B' U R' F' U' F",
    "F2 L F2 R U' R' U F' L' U F",
    "F' U F U2 R U R' F' U' F",
    "F' L' U L' B L B' L U F",
    4,
    "R B' R B R' U' R' U' F' U' F",
    "F' U2 F U R U2 R' U F' U' F",
    "F' U2 B L U L2 U' L B' U' F",
    "F' L2 U L' F L U' L' F2 L' F2",
    4,
    "F' U2 F U' R2 B' R' B U' R'",
    "F' U' L F' L' F2 U' R U2 R'",
    "F' U2 F2 R' F R L F2 L2 U2 L",
    "B U2 B2 R2 F B R F' R2 U2 R'",
    4,
    "R U R' U2 R U R' F' U F",
    "R U R' U2 R U' B U B' R'",
    "R U R' U' F' U L F' L' F2",
    "F' U L F U F' U' F' L' F2",
    4,
    "R U F' U' L' U L F R'",
    "R U2 B U B' R' U2 R U R'",
    "F' U F U2 F' L' U L U2 F",
    "F' U2 F U2 R B U' B' U' R'",
    4,
    "R2 B' R D' R' D R' B U R'",
    "U' R2 B' R' B U R' F R' F' R",
    "F R' F D' L' F L F2 D F' R",
    "F R' F' R U' R2 B' R' B U R'",
    3,
    "F' U F R' U' D' F2 U F2 D R",
    "F' U F R' D2 L2 U L2 U' D2 R",
    "F U F2 U F2 U2 F' R U R'",
    4,
    "R U2 B2 L' B' L U2 B' R'",
    "R U' R B' R' B2 U B' R'",
    "F' U F U F' L' U L U' F",
    "F' U F U' R U R' F' U F",
    4,
    "B U' R' F R F2 U B' U F",
    "F2 U' L U L F L' U' L' U2 F",
    "F' U R U' F' L F L' U R' F",
    "F' U R L' U B' U' B R' L F",
    4,
    "F' R' F2 L F2 R L' U F",
    "F' L' U L F U' F R' F' R",
    "R B U2 L U2 L' U B' R'",
    "R U2 B L U L' U B' R'",
    2,
    "R U L' B' R' D2 L2 F' L2 D2 L",
    "F2 U2 R' F D2 B2 L2 D2 R D2 L D2",
    4,
    "R U' R B' D' R D R2 B R'",
    "R U' B U2 L U L' B' U R'",
    "R' F D R' D' R2 F' R U' R'",
    "F' U2 L' U' L F U' R U' R'",
    4,
    "F' U' R U B U' B' R' F",
    "R U L' B' U' B U L U2 R'",
    "R U B U B' R' U2 F' U2 F",
    "F' U2 L' U' L F U2 F' U' F",
    4,
    "F2 L F L' U' F R' F R F'",
    "F2 L F' D F D' F L' U' F",
    "R U' B' R B R2 U R' F R F'",
    "R' F R F' U F2 L F L' U' F",
    3,
    "R F R' U R2 U' R' F' U' R'",
    "R B U' L U2 L' U' B' U' R'",
    "F' U L F R F2 L' F2 R U2 R2",
    4,
    "F' U F' L F L2 U' L F",
    "F' U2 L2 B L B' U2 L F",
    "R U B L U' L' U B' U R'",
    "R U2 B U' L' B L B2 U R'",
    4,
    "L' U F R' F' R2 U' L U' R'",
    "R U' F' U R B' R' B U' F R'",
    "R U' F' B U' L U L' F B' R'",
    "R2 U B' U' B' R' B U B U2 R'",
    4,
    "R F R2 B' R2 F' B U' R'",
    "R B U' B' R' U R' F R F'",
    "R U2 B L U' L' B' U R'",
    "F' U2 L' B' U' B U' L F",
    4,
    "D B' D' F D R' B D' F2 U' F",
    "B' R2 U' R' U F R2 F2 B U' F",
    "R U' R2 D' L F L' D R U R U' R'",
    "R2 F' U2 F U' R' U' F R2 F2 U' F",
    4,
    "R B U' B' U2 R' U' R U R'",
    "F B' R F' U F' U' F R' B",
    "R2 B L' B L B' U B' U' R2",
    "F' U2 F R U' R B' R' B U2 R'",
    4,
    "R B' R2 D' R' D R' B U R'",
    "R2 B R' U' B L U L' B2 U2 R'",
    "L U' F' U2 F U R' F2 R F2 L'",
    "F' L' U L U' L F' L' F2",
    4,
    "F2 L F L' U' F U R U2 R'",
    "F' U' F R U' R' U2 R U2 R'",
    "R B U' B' U R' U2 R U2 R'",
    "R U' B' R B R L F2 R F2 L'",
    4,
    "R L' B' U' B U L U2 R'",
    "L F2 R' F2 R L' U2 F' U' F",
    "R' L F D' F D R F2 L'",
    "F' U L' B' U2 B U2 L U2 F",
    4,
    "B U2 B2 R2 F B R F' R2 U R'",
    "F2 B2 D2 F' D2 B2 R' F' R2 U R'",
    "F' U' L' B L2 B' L2 U2 F' L F2",
    "F R2 L2 B2 D2 B2 R L2 F' R2 U R'",
    4,
    "F' L' U2 B L' B' L2 U' F",
    "R U R' F' U2 L F' L' F2",
    "R2 B' R' B U2 R' F' U F",
    "F' U L F' L' F' R' F' R",
    4,
    "R' D' L F L U2 D2 R2 D L2 D2 R'",
    "R' D' L F L D2 R' U2 R2 D L2 D2",
    "R' D' L F L D2 R' D2 L2 D R2",
    "R' D' L F L' U F2 U2 F2 U' D R",
    4,
    "L' U2 L2 F2 R' L' F' R F2 U' F",
    "R2 L2 D2 R D2 L2 F R F2 U' F",
    "R U B' R B R F2 D' F' D R F'",
    "R D2 R2 L2 U2 D2 L2 F R F2 U' F",
    4,
    "D' F2 U F2 D R2 U2 R2",
    "R2 U R2 D B2 U2 B2 D'",
    "R2 U2 D' F2 U F2 U D R2",
    "D B2 U B2 U2 D' R2 U2 R2",
    4,
    "D2 B' U R' U2 R U' B D2",
    "U' D R' U F' U2 F U' R D'",
    "R U2 B U' L U2 L' U B' R'",
    "F' U R' F2 L F2 R L' U F",
    4,
    "R2 B' R' B U2 R' U' R U R'",
    "D B2 L' B' L U2 B' U' B U B' D'",
    "R2 B' R' B2 L U' L' U2 B' U R'",
    "D R B' R' B2 U B' U' B U B' D'",
    3,
    "R U' R' U R U2 B' R B R2",
    "R U' B U2 L U L' B2 R B R2",
    "D' F U' F' U F U2 R' F R F2 D",
    4,
    "D2 B' U R' U R U' B D2",
    "R U2 B U B' U' B U B' R'",
    "F' U F U2 R U' B U B' R'",
    "F' U L F' D' L D L2 F2",
    4,
    "D B U' L U' L' U B' D'",
    "R U' R B' D' R D R' B R2",
    "R U' R' U R U' B' R B R2",
    "F' U2 L' U' L U' F R U' R'",
    3,
    "R U R' U' R U2 B' R B R2",
    "D2 L U L' U' L U' L2 B L B' D2",
    "D B U B' U' B U2 L' B L B2 D'",
    4,
    "D2 B' R' U2 R B U2 B L' B' L D2",
    "F' L' U' B L B' U' B' U B U2 F",
    "F' L' B' U' B L U2 L' U L U' F",
    "F' L' U2 L F U R2 B' R' B U R'",
    4,
    "D' F U F' U2 F U F' D",
    "R U R' F' L' U L U2 F",
    "R B' U2 B U B' U B U R'",
    "D2 L U L' U2 L U L' D2",
    4,
    "D' F U2 F' L' U L F U F' D",
    "D' F R U R' F' U2 F U F' D",
    "R U R' B' R2 U' R U R2 B",
    "R B U B' R' F' L' U L U2 F",
    4,
    "D B' U' D' R' U R D B D'",
    "R' U' R F' R' F' U F R F",
    "F' L' F' L U' L' U F L F",
    "D' F' U' D' L' U L D F D",
    3,
    "R U' R' U' R2 B' R' B U2 R'",
    "D B U' B' R B' R' B2 U B' D'",
    "R U2 B' R2 D' R' D R' B U2 R'",
    4,
    "R U2 B L U L' U' B' U' R'",
    "R U' R B U B' U' R' U2 R'",
    "D2 L U R B U B' U' R' L' D2",
    "D2 L B L U L' U' B' U L' D2",
    4,
    "D B U' L U L' U B' U2 D'",
    "R2 B2 D B D' R' B U R'",
    "F' U L F' L' F2 U2 R U R'",
    "D' F2 R2 D R D' F' R U F' D",
    4,
    "D' L' F' L2 B L2 F B' L D",
    "L F2 L' B L F L F L2 B'",
    "L' B' U' F' U' B U F U L",
    "R B U2 L U L' U2 B' R'",
    4,
    "R2 B' R' B U' R2 F R F'",
    "D' F2 R' F' R U' F2 L F L' D",
    "D2 L2 F' L' F U2 F' L F L2 D2",
    "D' L F' L' F2 U2 F2 L F L' D",
    4,
    "B U L D' L' U' L D L' B'",
    "L2 F' U' B2 U F U' B2 U L2",
    "R' U' R F' R' U R U' F",
    "D L D2 L' U' L D2 L' D'",
    4,
    "R2 B' R2 U' R U R B R2",
    "D' F2 R' F2 U' F U F R F2 D",
    "L U F2 U' R' D' F D R F L'",
    "L U D' F U' R' F R F2 D L'",
    4,
    "D B U L U L' U2 B' D'",
    "R U B U L U' L' U2 B' R'",
    "F R D2 B U' B' U D2 R' F'",
    "B U R L U L' U' R' U' B'",
    4,
    "F U2 L2 U2 R U R' U2 L2 U F'",
    "F' U' R' L' F2 D' L D F2 R L F",
    "L F U F' U' D' L' U L D L'",
    "B L U L' U' D2 B' U B D2 B'",
    4,
    "R' F R F' U F' U' F",
    "D R' U F' U' F U' R D'",
    "F2 L2 D' L' D F L' U' F",
    "F' U' F R U' B U' B' U2 R'",
    4,
    "R' F' U D2 L' U' L D2 F R",
    "L' U' F' U' B' U F B U L",
    "D2 B' U2 R' U R U B D2",
    "D R' U2 F' U F U R D'",
    4,
    "R U2 B L U2 L' U2 B' R'",
    "F' R' L F2 L' F2 R F",
    "U D' F R U2 R' U2 F' D",
    "D2 L F U2 F' U2 L' U D2",
    3,
    "R L' U B2 U B' U' B' U' B' R' L",
    "F' R B L B L' B' L' B' R' F",
    "B U B R D F' B' L' F D' B' R'",
    4,
    "R U' B' R' U' R U B R'",
    "F' U' F U F' U2 L' U' L F",
    "F' L U F U' F' L' U' F",
    "R U2 L' B' U' B U L U R'",
    4,
    "R U' B U B' R B' R' B R'",
    "R L U' R B' R' B R' U L'",
    "L F' U F U' R U' R' U L'",
    "L2 F' R U' R' U R' F R L2",
    4,
    "R U2 B U B' R' U' R U R'",
    "F' U F U' F' L' U L U2 F",
    "F R' D' F D F2 R U2 R U R'",
    "F' U F U2 F R2 D R D' F' R",
    4,
    "F2 L F L' U' F R U' R'",
    "F' U L' U B' U' B U' L F",
    "R U' B' R D' R D R2 B R'",
    "R U' B' R B R2 U R U' R'",
    2,
    "R U R' D' F2 U R' F R U' F2 D",
    "R B' R2 D' R' D B D L' B L D' R2",
    2,
    "L2 D F' D' R2 L2 B' R' U B U2 R'",
    "R2 D L' B L D' R' U R'",
    2,
    "F' U F R U R' U R' F R F'",
    "F' U F R U B U' B' U R'",
    4,
    "R U' F' U2 F2 R2 B' R2 B R' F'",
    "R U' B U2 B2 R2 F R2 B R' F'",
    "R U' B' R2 F B R2 F' U2 F R' F'",
    "R2 U B' U' R' U B R' F' U F",
    4,
    "R' F D R' D' R2 F2 U F",
    "F' U2 L2 B L B' U' L F",
    "B' R F' U F U' F R' F' B",
    "R U' B U2 L U L' U B' R'",
    4,
    "R U2 F' U' L' U L F U' R'",
    "R U' L' U' B' U B L U2 R'",
    "F' U2 B L U L' U' B' U' F",
    "F' U' R B U B' U' R' U2 F",
    4,
    "R2 B' R' B U R' F' U F",
    "R L' U R' F R' F' R U' L",
    "F R' D' F L D' L' D2 F2 R",
    "F' U L F' D F' D' F2 L' F",
    4,
    "R U' R' U R U B U B' R'",
    "F' U F' L F2 L' U' L' U L",
    "R U' R' U L F' U L F L' U' L'",
    "R U' R' F' U L U F U' F' L' F",
    2,
    "R U2 B' U' R B R2 L2 D F D' L2",
    "R U' R D L' B' L D' R2",
    4,
    "R U2 B' R B R2 U2 F' U F",
    "R U' R2 F R F' U F' U F",
    "F' U F' L F L2 U' L U F",
    "F' U2 L2 B L B' U2 L U F",
    4,
    "R U2 B U B' U2 B' R B R2",
    "R U2 B U B' U' R2 F R F'",
    "F' U F U2 R U2 B' R B R2",
    "F' U F U2 R U' R2 F R F'",
    3,
    "R U' R' F' U' L' U L U' F",
    "R U' R' F' U' F U2 R2 B' R' B U R'",
    "R U' R' F' U' L F' D' L D L2 F2",
    4,
    "R' U D2 L2 U' L2 D2 R F R' F' R",
    "R' U' R2 U' R2 U2 R F' U L F' L' F2",
    "R' F D' F D L2 D2 L' D2 L' F2 R",
    "R' D' F2 U' F2 U D R F R' F' R",
    2,
    "R U' R' U F' U2 L' U L U' F",
    "F' U2 L' U B' U' B U L U' F",
    4,
    "F2 U2 F U F' U F U2 F",
    "R U B U B' U B U2 B' U R'",
    "R U2 R U B U2 L U L' B' R2",
    "R U' F U F' U F U2 F' U' R'",
    1,
    "R U' B U B' U' R' U R U R'",
    4,
    "R U' R' U R U B' R B R2",
    "R' F R F2 U2 F U F' U' F",
    "F2 L F L' U F U F' U' F",
    "R U' B U2 L U L' B' R2 F R F'",
    2,
    "F R' F' R2 B U B2 R B R' U R'",
    "R2 B' R' B U B L' B L B2 U2 R'",
    2,
    "R U2 D' F' U' F U2 F' U' F D R'",
    "R D B' U' B U2 B' U' B U2 D' R'",
    2,
    "F' U L' U' L U F U' F' U' F",
    "R' F R F' U F' U F U' F' U' F",
    3,
    "R2 B' R' B U' R' U' R U R'",
    "F' U F U' F' U2 F2 R' F' R",
    "F' U F U' F' U' L F' L' F2",
    2,
    "F' R L' U B U' B L' B2 R' L2 F",
    "R U' R' U2 R2 D L' B' L D' R' U' R'",
    4,
    "R2 B' R' B R' U2 F' U' F",
    "R2 B' D B' D' B2 R' U R'",
    "F' U F' L2 D' L' D L' F2",
    "F' U2 L' B L' B' L2 U' F",
    4,
    "R U' R' F' U2 R' L F2 L' F2 R F",
    "R U' R' F' R' F2 L F2 R L' U2 F",
    "R U' R' F' L' B' U' B L U2 F",
    "R U' R' L F' D' L' U2 L D F L'",
    4,
    "R U2 B U L U' L' B' U R'",
    "B R U' R U B U' B' R2 B'",
    "B2 R U' R U B U' B' R2 B2",
    "B' R U' R U B U' B' R2 B",
    4,
    "F' U2 L' B' U B L F R U R'",
    "F' U2 R' L F2 L' F2 R F R U R'",
    "F' R' F2 L F2 R L' U2 F R U R'",
    "F' L' U2 F' L D F R U F R' D"];

sessionStorage.setItem("scrambles", JSON.stringify(scrambleArray));
